---
{{- $fullname := include "database.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}
data:
  my.cnf: |
    [client]
    default-character-set=utf8mb3

    [mysql]
    default-character-set=utf8mb3

    [mysqld]
    bind-address=0.0.0.0
    init-connect='SET NAMES utf8mb3'
    character-set-server=utf8mb3

    max_allowed_packet=100M

    #we don't want STRICT_TRANS_TABLES as it causes a lot of problems with record-macros. https://github.com/HaxeFoundation/record-macros/issues/23
    sql-mode='ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    #default in 5.7 is sql-mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

    #
    # Fine Tuning
    #
    [mysqld]
    key_buffer_size         = 16M
    read_buffer_size        = 60K
    sort_buffer_size        = 1M
    innodb_buffer_pool_size = 64M
    tmp_table_size          = 8M
    max_allowed_packet      = 16M
    thread_stack            = 192K
    thread_cache_size       = 8

    # This replaces the startup script and checks MyISAM tables if needed
    # the first time they are touched
    myisam-recover-options  = BACKUP
    max_connections         = 25


--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "database.fullname" . }}-scripts
data:
  backup.sh: |
    #! /bin/bash

    mysqldump --hex-blob --no-tablespaces -u docker -pdocker db > ${SQL_FILE}
    exit 0
