{{- if .Values.webapp.ingress.enabled -}}
{{- $fullName := include "webapp.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
  {{- with .Values.webapp.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.webapp.ingress.className }}
  ingressClassName: {{ .Values.webapp.ingress.className }}
  {{- end }}
  {{- range $host := .Values.webapp.ingress.hosts }}
  tls:
    - hosts:
        - {{ $host.name | quote }}
      secretName: {{ $host.name }}-tls
  rules:
    - host: {{ $host.name }}
      http:
        paths:
          - path: {{ $host.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  {{ with index $.Values.webapp.service.ports 0 }}
                  number: {{ .port }}
                  {{ end }}
      {{- end }}
{{- end }}