{{- $fullName := include "webapp.fullname" . -}}

{{- if .Values.webapp.env_as_secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $fullName }}-webapp
  annotations:
    # this is because the name is a deployment time parameter
    # consider also using "cluster-wide" if the namespace is also a parameter
    # please make sure you understand the implications, see README
    sealedsecrets.bitnami.com/force-managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
  {{- range $key, $val := .Values.webapp.env_as_secrets }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end -}}