{{- $fullname := include "webapp.fullname" . -}}

{{- if .Values.webapp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
  {{- with .Values.webapp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}